### ISSUE TITLE
Python version for this project

### ISSUE THREAD

**Issue by Zhangshibf** [voithru/voice-activity-detection#6]
Good evening,
May I know what Python version is used for this project? I'm having problem with environment settings.
Thank you

**Comment by skxooo** [comment]
> Good evening, May I know what Python version is used for this project? I'm having problem with environment settings. Thank you

I have the same question.

**Comment by Zhangshibf** [comment]
Not sure what python version did they exactly use. In the end I used PYTHON==3.6.12 and had no problems
